# Sidebar navigation

- label: 'General'
  items:
    - label: 'Introduction'
      link: '/'
    - label: 'Github'
      link: 'https://github.com/JagrKt/'
    - label: 'TeamCity'
      link: 'http://ci.anvilpowered.org'
- label: 'Rubric'
  items:
    - label: 'Overview'
      link: '/rubric/overview'
    - label: 'Criterion Overview'
      link: '/rubric/criterion_overview'
    - label: 'Rubric Builder'
      link: '/rubric/rubric_builder'
    - label: 'Criterion Builder'
      link: '/rubric/criterion_builder'
- label: 'Grader'
  items:
    - label: 'Getting Started'
      link: '/grader/getting_started'
